.\" Manpage for traqtor
.\" Contact thelight.mn@gmail.com to correct errors or typos.
.TH man 1 "15 Apr 2019" "1.1" "traqtor man page"
.SH NAME
traqtor \- Settings for traktr
.SH SYNOPSIS
traqtor
.SH DESCRIPTION
This is a graphical settings app for tractor which is a package uses Python stem library to provide a connection through the onion proxy and sets up proxy in user session, so you don't have to mess up with TOR on your system anymore.
.SH AUTHOR
Mohsen Nezammolmolki (thelight.mn@gmail.com)
